version: "3.9"

services:
  postgres_tc:
    container_name: postgres_tc
    image: postgres:15.0-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  strapi_tc:
    container_name: strapi_tc
    image: strapi
    build: .
    restart: always
    env_file:
      - .env
    command: sh -c "npm run build --clean && npm run develop"
    depends_on:
      - postgres_tc
    environment:
      WAIT_HOSTS: postgres_tc:5432
    ports:
      - "49750:49750"
    volumes:
      - src:/app/src/

volumes:
  pgdata:
  src:
