name: remote ssh command
on: 
  push:
    branches:
      - main
    paths-ignore:
      - .editorconfig
      - .gitignore
      - README.md
      - .github
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /usr/local/transport-cms/transport-cms
          git checkout main
          git pull
          make all
